title:  "balte.nl"
tagline: "A personal space on the web"

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Projects', folder: 'pages', file: 'resources.html'}
- {name: 'Blog', folder: 'pages', file: 'sample-posts.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/_balte'}
- {icon: 'envelope', link: 'mailto:contact@balte.nl'}
- {icon: 'github', link: 'https://github.com/baltedewit'}
- {icon: 'rss-square', link: 'feed.xml'}
